import { defineStore } from 'pinia'
import type { Stream } from '~~/types/channel'
import type { Category } from '~~/types/category'

export const useChannelsStore = defineStore('channels', () => {
  const isOpen = ref(true)
  const channels = ref([
    {
      id: 1,
      name: 'Ibai',
      category: 'Just Chatting',
      viewers: 132000,
      isLive: true,
      avatar: 'https://placehold.co/32x32',
    },
    {
      id: 2,
      name: 'AuronPlay',
      category: 'GTA V',
      viewers: 89400,
      isLive: true,
      avatar: 'https://placehold.co/32x32',
    },
    {
      id: 3,
      name: 'TheGrefg',
      category: 'Fortnite',
      viewers: 41000,
      isLive: false,
      avatar: 'https://placehold.co/32x32',
    },
    {
      id: 4,
      name: 'Gaymer_Chris',
      category: 'Just Chatting',
      viewers: 8700,
      isLive: true,
      avatar: 'https://placehold.co/32x32',
    },
    {
      id: 5,
      name: 'Knekro',
      category: 'Resident Evil',
      viewers: 3200,
      isLive: true,
      avatar: 'https://placehold.co/32x32',
    },
    {
      id: 6,
      name: 'Outconsumer',
      category: 'Software & Game Dev',
      viewers: 980,
      isLive: false,
      avatar: 'https://placehold.co/32x32',
    },
    {
      id: 7,
      name: 'Midudev',
      category: 'Coding Live',
      viewers: 420,
      isLive: true,
      avatar: 'https://placehold.co/32x32',
    },
    {
      id: 8,
      name: 'Spok',
      category: 'Valorant',
      viewers: 210,
      isLive: true,
      avatar: 'https://placehold.co/32x32',
    },
    {
      id: 9,
      name: 'Rojuu',
      category: 'League of Legends',
      viewers: 87,
      isLive: false,
      avatar: 'https://placehold.co/32x32',
    },
    {
      id: 10,
      name: 'Rivers_gg',
      category: 'Chess',
      viewers: 12,
      isLive: true,
      avatar: 'https://placehold.co/32x32',
    },
  ])

  const streams = ref<Stream[]>([
    {
      id: 1,
      title: 'BARCELONA 4 REAL MADRID 0 | ¡HANSI FLICK ES UN GENIO!',
      streamer: 'Ibai',
      category: 'Just Chatting',
      viewers: 132000,
      isLive: true,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español', 'DropsActivados'],
    },
    {
      id: 2,
      title: 'GTA RP - El mejor servidor de España',
      streamer: 'AuronPlay',
      category: 'GTA V',
      viewers: 89400,
      isLive: true,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español', 'IRL'],
    },
    {
      id: 3,
      title: 'RANKED hasta Challenger o me rajo el pelo',
      streamer: 'Rojuu',
      category: 'League of Legends',
      viewers: 9800,
      isLive: true,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español'],
    },
    {
      id: 4,
      title: 'Resident Evil 4 Remake - Hardcore sin morir',
      streamer: 'Knekro',
      category: 'Resident Evil',
      viewers: 3200,
      isLive: false,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español', 'DropsActivados'],
    },
    {
      id: 5,
      title: 'Construyendo un clon de Twitch en directo',
      streamer: 'Midudev',
      category: 'Software & Game Dev',
      viewers: 2300,
      isLive: true,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español', 'Programación'],
    },
    {
      id: 6,
      title: 'Torneo de ajedrez con suscriptores',
      streamer: 'Rivers_gg',
      category: 'Chess',
      viewers: 4100,
      isLive: true,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español'],
    },
    {
      id: 7,
      title: 'Valorant ranked con viewers - !discord',
      streamer: 'Spok',
      category: 'Valorant',
      viewers: 210,
      isLive: false,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español', 'DropsActivados'],
    },
    {
      id: 8,
      title: 'FIFA 25 - Ultimate Team grinding',
      streamer: 'TheGrefg',
      category: 'FIFA 25',
      viewers: 41000,
      isLive: true,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español'],
    },
    {
      id: 9,
      title: 'Fortnite con los mejores del mundo',
      streamer: 'Gaymer_Chris',
      category: 'Fortnite',
      viewers: 8700,
      isLive: true,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español', 'DropsActivados'],
    },
    {
      id: 10,
      title: 'Open source en vivo - PR reviews',
      streamer: 'Outconsumer',
      category: 'Software & Game Dev',
      viewers: 980,
      isLive: false,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español', 'Programación'],
    },
    {
      id: 11,
      title: 'Open source en vivo - PR reviews',
      streamer: 'Outconsumer',
      category: 'Software & Game Dev',
      viewers: 980,
      isLive: false,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español', 'Programación'],
    },
    {
      id: 12,
      title: 'Open source en vivo - PR reviews',
      streamer: 'Outconsumer',
      category: 'Software & Game Dev',
      viewers: 980,
      isLive: false,
      thumbnail: 'https://placehold.co/320x180',
      avatar: 'https://placehold.co/32x32',
      tags: ['Español', 'Programación'],
    },
  ])

  const categories = ref<Category[]>([
    {
      id: 1,
      name: 'Just Chatting',
      viewers: 285000,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['IRL'],
    },
    {
      id: 2,
      name: 'Software & Game Dev',
      viewers: 21000,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Software', 'IRL'],
    },
    {
      id: 3,
      name: 'Farming Simulator 25',
      viewers: 3600,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Simulation'],
    },
    {
      id: 4,
      name: 'S.T.A.L.K.E.R. 2',
      viewers: 1400,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Gaming'],
    },
    {
      id: 5,
      name: 'Towers of Aghasba',
      viewers: 23000,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Gaming'],
    },
    {
      id: 6,
      name: 'Flight Simulator 2024',
      viewers: 12000,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Simulation'],
    },
    {
      id: 7,
      name: 'League of Legends',
      viewers: 180000,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Esports', 'Gaming'],
    },
    {
      id: 8,
      name: 'Valorant',
      viewers: 95000,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Esports', 'Gaming'],
    },
    {
      id: 9,
      name: 'Minecraft',
      viewers: 72000,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Gaming'],
    },
    {
      id: 10,
      name: 'Chess',
      viewers: 8400,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Esports'],
    },
    {
      id: 11,
      name: 'Grand Theft Auto V',
      viewers: 110000,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Gaming', 'IRL'],
    },
    {
      id: 12,
      name: 'Fortnite',
      viewers: 88000,
      thumbnail: 'https://placehold.co/140x190',
      tags: ['Gaming', 'Esports'],
    },
  ])
  return { channels, isOpen, streams, categories }
})
